///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package purchasehub_supplier_order_goods_merge_repo

import (
	"fmt"
	"time"

	"go_service/repository/db_repo"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *PurchasehubSupplierOrderGoodsMerge {
	return new(PurchasehubSupplierOrderGoodsMerge)
}

func NewQueryBuilder() *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	return new(purchasehubSupplierOrderGoodsMergeRepoQueryBuilder)
}

func (t *PurchasehubSupplierOrderGoodsMerge) Create(db *gorm.DB) (id int32, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type purchasehubSupplierOrderGoodsMergeRepoQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&PurchasehubSupplierOrderGoodsMerge{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&PurchasehubSupplierOrderGoodsMerge{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&PurchasehubSupplierOrderGoodsMerge{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) First(db *gorm.DB) (*PurchasehubSupplierOrderGoodsMerge, error) {
	ret := &PurchasehubSupplierOrderGoodsMerge{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) QueryOne(db *gorm.DB) (*PurchasehubSupplierOrderGoodsMerge, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) QueryAll(db *gorm.DB) ([]*PurchasehubSupplierOrderGoodsMerge, error) {
	var ret []*PurchasehubSupplierOrderGoodsMerge
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) Limit(limit int) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) Offset(offset int) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) WhereId(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) WhereIdIn(value []int32) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) WhereIdNotIn(value []int32) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) OrderById(asc bool) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) WherePhsoid(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsoid", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) WherePhsoidIn(value []int32) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsoid", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) WherePhsoidNotIn(value []int32) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsoid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) OrderByPhsoid(asc bool) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "phsoid "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) WhereDetails(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "details", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) WhereDetailsIn(value []string) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "details", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) WhereDetailsNotIn(value []string) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "details", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) OrderByDetails(asc bool) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "details "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) WhereCreatedAt(p db_repo.Predicate, value time.Time) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) WhereCreatedAtIn(value []time.Time) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) WhereCreatedAtNotIn(value []time.Time) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) OrderByCreatedAt(asc bool) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "created_at "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) WhereUpdatedAt(p db_repo.Predicate, value time.Time) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) WhereUpdatedAtIn(value []time.Time) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) WhereUpdatedAtNotIn(value []time.Time) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder) OrderByUpdatedAt(asc bool) *purchasehubSupplierOrderGoodsMergeRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "updated_at "+order)
	return qb
}
