///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package purchasehub_supplier_order_stockout_type_index_repo

import (
	"fmt"
	"time"

	"go_service/repository/db_repo"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *PurchasehubSupplierOrderStockoutTypeIndex {
	return new(PurchasehubSupplierOrderStockoutTypeIndex)
}

func NewQueryBuilder() *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	return new(purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder)
}

func (t *PurchasehubSupplierOrderStockoutTypeIndex) Create(db *gorm.DB) (id int32, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&PurchasehubSupplierOrderStockoutTypeIndex{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&PurchasehubSupplierOrderStockoutTypeIndex{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&PurchasehubSupplierOrderStockoutTypeIndex{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) First(db *gorm.DB) (*PurchasehubSupplierOrderStockoutTypeIndex, error) {
	ret := &PurchasehubSupplierOrderStockoutTypeIndex{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) QueryOne(db *gorm.DB) (*PurchasehubSupplierOrderStockoutTypeIndex, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) QueryAll(db *gorm.DB) ([]*PurchasehubSupplierOrderStockoutTypeIndex, error) {
	var ret []*PurchasehubSupplierOrderStockoutTypeIndex
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) Limit(limit int) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) Offset(offset int) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) WhereId(p db_repo.Predicate, value int32) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) WhereIdIn(value []int32) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) WhereIdNotIn(value []int32) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) OrderById(asc bool) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) WhereStockoutType(p db_repo.Predicate, value int32) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "stockout_type", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) WhereStockoutTypeIn(value []int32) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "stockout_type", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) WhereStockoutTypeNotIn(value []int32) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "stockout_type", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) OrderByStockoutType(asc bool) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "stockout_type "+order)
	return qb
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) WherePhsoid(p db_repo.Predicate, value int32) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsoid", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) WherePhsoidIn(value []int32) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsoid", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) WherePhsoidNotIn(value []int32) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsoid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) OrderByPhsoid(asc bool) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "phsoid "+order)
	return qb
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) WhereUpdatedAt(p db_repo.Predicate, value time.Time) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) WhereUpdatedAtIn(value []time.Time) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) WhereUpdatedAtNotIn(value []time.Time) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) OrderByUpdatedAt(asc bool) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "updated_at "+order)
	return qb
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) WhereCreatedAt(p db_repo.Predicate, value time.Time) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) WhereCreatedAtIn(value []time.Time) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) WhereCreatedAtNotIn(value []time.Time) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder) OrderByCreatedAt(asc bool) *purchasehubSupplierOrderStockoutTypeIndexRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "created_at "+order)
	return qb
}
