///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package purchasehub_supplier_order_goods_repo

import (
	"fmt"
	"time"

	"go_service/repository/db_repo"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *PurchasehubSupplierOrderGoods {
	return new(PurchasehubSupplierOrderGoods)
}

func NewQueryBuilder() *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	return new(purchasehubSupplierOrderGoodsRepoQueryBuilder)
}

func (t *PurchasehubSupplierOrderGoods) Create(db *gorm.DB) (id int32, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type purchasehubSupplierOrderGoodsRepoQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&PurchasehubSupplierOrderGoods{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&PurchasehubSupplierOrderGoods{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&PurchasehubSupplierOrderGoods{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) First(db *gorm.DB) (*PurchasehubSupplierOrderGoods, error) {
	ret := &PurchasehubSupplierOrderGoods{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) QueryOne(db *gorm.DB) (*PurchasehubSupplierOrderGoods, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) QueryAll(db *gorm.DB) ([]*PurchasehubSupplierOrderGoods, error) {
	var ret []*PurchasehubSupplierOrderGoods
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) Limit(limit int) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) Offset(offset int) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePhsogid(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsogid", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePhsogidIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsogid", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePhsogidNotIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsogid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByPhsogid(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "phsogid "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePhsoid(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsoid", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePhsoidIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsoid", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePhsoidNotIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsoid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByPhsoid(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "phsoid "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePhoid(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phoid", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePhoidIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phoid", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePhoidNotIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phoid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByPhoid(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "phoid "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereErpBillnumber(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "erp_billnumber", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereErpBillnumberIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "erp_billnumber", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereErpBillnumberNotIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "erp_billnumber", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByErpBillnumber(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "erp_billnumber "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereGoodsId(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_id", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereGoodsIdIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_id", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereGoodsIdNotIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByGoodsId(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "goods_id "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereGoodsSn(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_sn", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereGoodsSnIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_sn", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereGoodsSnNotIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_sn", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByGoodsSn(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "goods_sn "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereGoodsName(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_name", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereGoodsNameIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_name", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereGoodsNameNotIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_name", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByGoodsName(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "goods_name "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereGoodsImg(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_img", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereGoodsImgIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_img", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereGoodsImgNotIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_img", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByGoodsImg(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "goods_img "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereOnSaleTime(p db_repo.Predicate, value time.Time) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "on_sale_time", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereOnSaleTimeIn(value []time.Time) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "on_sale_time", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereOnSaleTimeNotIn(value []time.Time) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "on_sale_time", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByOnSaleTime(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "on_sale_time "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereColor(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "color", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereColorIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "color", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereColorNotIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "color", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByColor(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "color "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePrice(p db_repo.Predicate, value float64) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "price", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePriceIn(value []float64) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "price", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePriceNotIn(value []float64) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "price", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByPrice(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "price "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereInPrice(p db_repo.Predicate, value float64) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "in_price", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereInPriceIn(value []float64) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "in_price", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereInPriceNotIn(value []float64) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "in_price", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByInPrice(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "in_price "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereProductLine(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "product_line", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereProductLineIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "product_line", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereProductLineNotIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "product_line", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByProductLine(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "product_line "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaseQuantity(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_quantity", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaseQuantityIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_quantity", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaseQuantityNotIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_quantity", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByPurchaseQuantity(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "purchase_quantity "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaseAmount(p db_repo.Predicate, value float64) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_amount", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaseAmountIn(value []float64) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_amount", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaseAmountNotIn(value []float64) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_amount", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByPurchaseAmount(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "purchase_amount "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaseOrderQuantity(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_quantity", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaseOrderQuantityIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_quantity", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaseOrderQuantityNotIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_quantity", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByPurchaseOrderQuantity(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "purchase_order_quantity "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaseOrderPrice(p db_repo.Predicate, value float64) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_price", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaseOrderPriceIn(value []float64) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_price", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaseOrderPriceNotIn(value []float64) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_price", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByPurchaseOrderPrice(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "purchase_order_price "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaseOrderAmount(p db_repo.Predicate, value float64) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_amount", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaseOrderAmountIn(value []float64) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_amount", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaseOrderAmountNotIn(value []float64) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_amount", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByPurchaseOrderAmount(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "purchase_order_amount "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereSkuCount(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sku_count", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereSkuCountIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sku_count", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereSkuCountNotIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sku_count", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderBySkuCount(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "sku_count "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereDeveloperUid(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "developer_uid", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereDeveloperUidIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "developer_uid", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereDeveloperUidNotIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "developer_uid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByDeveloperUid(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "developer_uid "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereDeveloperName(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "developer_name", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereDeveloperNameIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "developer_name", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereDeveloperNameNotIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "developer_name", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByDeveloperName(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "developer_name "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaserId(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchaser_id", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaserIdIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchaser_id", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaserIdNotIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchaser_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByPurchaserId(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "purchaser_id "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaserUid(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchaser_uid", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaserUidIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchaser_uid", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaserUidNotIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchaser_uid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByPurchaserUid(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "purchaser_uid "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaserName(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchaser_name", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaserNameIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchaser_name", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WherePurchaserNameNotIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchaser_name", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByPurchaserName(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "purchaser_name "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereSupplyType(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supply_type", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereSupplyTypeIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supply_type", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereSupplyTypeNotIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supply_type", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderBySupplyType(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "supply_type "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereSupplyStatus(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supply_status", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereSupplyStatusIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supply_status", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereSupplyStatusNotIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supply_status", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderBySupplyStatus(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "supply_status "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereSuppSn(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supp_sn", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereSuppSnIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supp_sn", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereSuppSnNotIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supp_sn", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderBySuppSn(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "supp_sn "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereSuppUrl(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supp_url", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereSuppUrlIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supp_url", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereSuppUrlNotIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supp_url", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderBySuppUrl(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "supp_url "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereSuppliersName(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "suppliers_name", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereSuppliersNameIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "suppliers_name", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereSuppliersNameNotIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "suppliers_name", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderBySuppliersName(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "suppliers_name "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereSuppliersGoodsImg(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "suppliers_goods_img", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereSuppliersGoodsImgIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "suppliers_goods_img", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereSuppliersGoodsImgNotIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "suppliers_goods_img", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderBySuppliersGoodsImg(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "suppliers_goods_img "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereUpdatedAt(p db_repo.Predicate, value time.Time) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereUpdatedAtIn(value []time.Time) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereUpdatedAtNotIn(value []time.Time) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByUpdatedAt(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "updated_at "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereCreatedAt(p db_repo.Predicate, value time.Time) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereCreatedAtIn(value []time.Time) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereCreatedAtNotIn(value []time.Time) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByCreatedAt(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "created_at "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereProductType(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "product_type", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereProductTypeIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "product_type", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereProductTypeNotIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "product_type", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByProductType(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "product_type "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereFirstOrder(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "first_order", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereFirstOrderIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "first_order", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereFirstOrderNotIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "first_order", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByFirstOrder(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "first_order "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereIsExaminePrice(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_examine_price", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereIsExaminePriceIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_examine_price", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereIsExaminePriceNotIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_examine_price", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByIsExaminePrice(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "is_examine_price "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereExaminePriceResult(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "examine_price_result", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereExaminePriceResultIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "examine_price_result", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereExaminePriceResultNotIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "examine_price_result", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByExaminePriceResult(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "examine_price_result "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereExaminePriceKey(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "examine_price_key", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereExaminePriceKeyIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "examine_price_key", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereExaminePriceKeyNotIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "examine_price_key", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByExaminePriceKey(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "examine_price_key "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereExaminePriceData(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "examine_price_data", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereExaminePriceDataIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "examine_price_data", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereExaminePriceDataNotIn(value []string) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "examine_price_data", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByExaminePriceData(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "examine_price_data "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereStockoutType(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "stockout_type", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereStockoutTypeIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "stockout_type", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) WhereStockoutTypeNotIn(value []int32) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "stockout_type", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsRepoQueryBuilder) OrderByStockoutType(asc bool) *purchasehubSupplierOrderGoodsRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "stockout_type "+order)
	return qb
}
