///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package purchasehub_supplier_order_repo

import (
	"fmt"
	"time"

	"go_service/repository/db_repo"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *PurchasehubSupplierOrder {
	return new(PurchasehubSupplierOrder)
}

func NewQueryBuilder() *purchasehubSupplierOrderRepoQueryBuilder {
	return new(purchasehubSupplierOrderRepoQueryBuilder)
}

func (t *PurchasehubSupplierOrder) Create(db *gorm.DB) (id int32, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Phsoid, nil
}

type purchasehubSupplierOrderRepoQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&PurchasehubSupplierOrder{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&PurchasehubSupplierOrder{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&PurchasehubSupplierOrder{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) First(db *gorm.DB) (*PurchasehubSupplierOrder, error) {
	ret := &PurchasehubSupplierOrder{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) QueryOne(db *gorm.DB) (*PurchasehubSupplierOrder, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) QueryAll(db *gorm.DB) ([]*PurchasehubSupplierOrder, error) {
	var ret []*PurchasehubSupplierOrder
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) Limit(limit int) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) Offset(offset int) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePhsoid(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsoid", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePhsoidIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsoid", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePhsoidNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsoid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByPhsoid(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "phsoid "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePhoid(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phoid", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePhoidIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phoid", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePhoidNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phoid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByPhoid(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "phoid "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSupplierId(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supplier_id", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSupplierIdIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supplier_id", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSupplierIdNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supplier_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderBySupplierId(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "supplier_id "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereTargetContextId(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "target_context_id", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereTargetContextIdIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "target_context_id", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereTargetContextIdNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "target_context_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByTargetContextId(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "target_context_id "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereTargetContextType(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "target_context_type", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereTargetContextTypeIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "target_context_type", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereTargetContextTypeNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "target_context_type", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByTargetContextType(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "target_context_type "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereTargetContextCustom(p db_repo.Predicate, value string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "target_context_custom", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereTargetContextCustomIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "target_context_custom", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereTargetContextCustomNotIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "target_context_custom", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByTargetContextCustom(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "target_context_custom "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereErpBillnumber(p db_repo.Predicate, value string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "erp_billnumber", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereErpBillnumberIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "erp_billnumber", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereErpBillnumberNotIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "erp_billnumber", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByErpBillnumber(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "erp_billnumber "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereAlibabaOrderId(p db_repo.Predicate, value string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "alibaba_order_id", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereAlibabaOrderIdIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "alibaba_order_id", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereAlibabaOrderIdNotIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "alibaba_order_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByAlibabaOrderId(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "alibaba_order_id "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePurchaseQuantity(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_quantity", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePurchaseQuantityIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_quantity", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePurchaseQuantityNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_quantity", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByPurchaseQuantity(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "purchase_quantity "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePurchaseAmount(p db_repo.Predicate, value float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_amount", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePurchaseAmountIn(value []float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_amount", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePurchaseAmountNotIn(value []float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_amount", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByPurchaseAmount(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "purchase_amount "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePurchaseOrderQuantity(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_quantity", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePurchaseOrderQuantityIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_quantity", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePurchaseOrderQuantityNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_quantity", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByPurchaseOrderQuantity(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "purchase_order_quantity "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePurchaseOrderAmount(p db_repo.Predicate, value float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_amount", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePurchaseOrderAmountIn(value []float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_amount", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePurchaseOrderAmountNotIn(value []float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_amount", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByPurchaseOrderAmount(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "purchase_order_amount "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsDeleted(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_deleted", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsDeletedIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_deleted", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsDeletedNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_deleted", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByIsDeleted(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "is_deleted "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereStatus(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereStatusIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereStatusNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByStatus(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "status "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereCreatedUid(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_uid", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereCreatedUidIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_uid", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereCreatedUidNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_uid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByCreatedUid(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "created_uid "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereCreatedNickname(p db_repo.Predicate, value string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_nickname", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereCreatedNicknameIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_nickname", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereCreatedNicknameNotIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_nickname", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByCreatedNickname(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "created_nickname "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereUpdatedAt(p db_repo.Predicate, value time.Time) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereUpdatedAtIn(value []time.Time) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereUpdatedAtNotIn(value []time.Time) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByUpdatedAt(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "updated_at "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereCreatedAt(p db_repo.Predicate, value time.Time) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereCreatedAtIn(value []time.Time) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereCreatedAtNotIn(value []time.Time) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByCreatedAt(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "created_at "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereDeletedAt(p db_repo.Predicate, value time.Time) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_at", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereDeletedAtIn(value []time.Time) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_at", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereDeletedAtNotIn(value []time.Time) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByDeletedAt(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "deleted_at "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereType(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "type", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereTypeIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "type", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereTypeNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "type", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByType(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "type "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereProductLine(p db_repo.Predicate, value string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "product_line", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereProductLineIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "product_line", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereProductLineNotIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "product_line", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByProductLine(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "product_line "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereNeedCallback(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "need_callback", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereNeedCallbackIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "need_callback", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereNeedCallbackNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "need_callback", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByNeedCallback(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "need_callback "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereCateId(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "cate_id", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereCateIdIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "cate_id", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereCateIdNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "cate_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByCateId(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "cate_id "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereCateText(p db_repo.Predicate, value string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "cate_text", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereCateTextIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "cate_text", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereCateTextNotIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "cate_text", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByCateText(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "cate_text "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereMergeTargetPhsoid(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "merge_target_phsoid", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereMergeTargetPhsoidIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "merge_target_phsoid", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereMergeTargetPhsoidNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "merge_target_phsoid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByMergeTargetPhsoid(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "merge_target_phsoid "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereMergeSourcePhsoid(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "merge_source_phsoid", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereMergeSourcePhsoidIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "merge_source_phsoid", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereMergeSourcePhsoidNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "merge_source_phsoid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByMergeSourcePhsoid(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "merge_source_phsoid "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsMerged(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_merged", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsMergedIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_merged", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsMergedNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_merged", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByIsMerged(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "is_merged "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsMerge(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_merge", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsMergeIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_merge", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsMergeNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_merge", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByIsMerge(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "is_merge "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsPull(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_pull", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsPullIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_pull", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsPullNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_pull", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByIsPull(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "is_pull "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereStoreName(p db_repo.Predicate, value string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "store_name", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereStoreNameIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "store_name", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereStoreNameNotIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "store_name", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByStoreName(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "store_name "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereDeletedNickname(p db_repo.Predicate, value string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_nickname", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereDeletedNicknameIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_nickname", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereDeletedNicknameNotIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_nickname", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByDeletedNickname(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "deleted_nickname "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereDeletedUid(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_uid", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereDeletedUidIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_uid", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereDeletedUidNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deleted_uid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByDeletedUid(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "deleted_uid "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereCallbackType(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "callback_type", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereCallbackTypeIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "callback_type", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereCallbackTypeNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "callback_type", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByCallbackType(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "callback_type "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereDemandManageUid(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "demand_manage_uid", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereDemandManageUidIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "demand_manage_uid", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereDemandManageUidNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "demand_manage_uid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByDemandManageUid(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "demand_manage_uid "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereDemandManageNickname(p db_repo.Predicate, value string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "demand_manage_nickname", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereDemandManageNicknameIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "demand_manage_nickname", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereDemandManageNicknameNotIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "demand_manage_nickname", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByDemandManageNickname(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "demand_manage_nickname "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSupplierAbbreviation(p db_repo.Predicate, value string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supplier_abbreviation", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSupplierAbbreviationIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supplier_abbreviation", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSupplierAbbreviationNotIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supplier_abbreviation", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderBySupplierAbbreviation(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "supplier_abbreviation "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSupplierFullName(p db_repo.Predicate, value string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supplier_full_name", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSupplierFullNameIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supplier_full_name", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSupplierFullNameNotIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supplier_full_name", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderBySupplierFullName(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "supplier_full_name "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSuppliersType(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "suppliers_type", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSuppliersTypeIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "suppliers_type", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSuppliersTypeNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "suppliers_type", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderBySuppliersType(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "suppliers_type "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereOrderTypeId(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "order_type_id", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereOrderTypeIdIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "order_type_id", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereOrderTypeIdNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "order_type_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByOrderTypeId(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "order_type_id "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSettlementMethodId(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "settlement_method_id", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSettlementMethodIdIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "settlement_method_id", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSettlementMethodIdNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "settlement_method_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderBySettlementMethodId(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "settlement_method_id "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSkuCount(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sku_count", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSkuCountIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sku_count", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSkuCountNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sku_count", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderBySkuCount(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "sku_count "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereGoodsCount(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_count", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereGoodsCountIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_count", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereGoodsCountNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_count", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByGoodsCount(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "goods_count "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereStockInQuantity(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "stock_in_quantity", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereStockInQuantityIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "stock_in_quantity", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereStockInQuantityNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "stock_in_quantity", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByStockInQuantity(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "stock_in_quantity "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereStockInAmount(p db_repo.Predicate, value float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "stock_in_amount", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereStockInAmountIn(value []float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "stock_in_amount", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereStockInAmountNotIn(value []float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "stock_in_amount", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByStockInAmount(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "stock_in_amount "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereDiscountMoney(p db_repo.Predicate, value float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "discount_money", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereDiscountMoneyIn(value []float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "discount_money", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereDiscountMoneyNotIn(value []float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "discount_money", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByDiscountMoney(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "discount_money "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereExpressFee(p db_repo.Predicate, value float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "express_fee", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereExpressFeeIn(value []float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "express_fee", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereExpressFeeNotIn(value []float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "express_fee", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByExpressFee(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "express_fee "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereTimeFee(p db_repo.Predicate, value float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "time_fee", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereTimeFeeIn(value []float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "time_fee", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereTimeFeeNotIn(value []float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "time_fee", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByTimeFee(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "time_fee "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereRefundFee(p db_repo.Predicate, value float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "refund_fee", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereRefundFeeIn(value []float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "refund_fee", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereRefundFeeNotIn(value []float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "refund_fee", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByRefundFee(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "refund_fee "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSpecialLogisticsCostsTotal(p db_repo.Predicate, value float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "special_logistics_costs_total", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSpecialLogisticsCostsTotalIn(value []float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "special_logistics_costs_total", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSpecialLogisticsCostsTotalNotIn(value []float64) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "special_logistics_costs_total", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderBySpecialLogisticsCostsTotal(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "special_logistics_costs_total "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePurchaserId(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchaser_id", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePurchaserIdIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchaser_id", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePurchaserIdNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchaser_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByPurchaserId(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "purchaser_id "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePurchaserUid(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchaser_uid", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePurchaserUidIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchaser_uid", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePurchaserUidNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchaser_uid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByPurchaserUid(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "purchaser_uid "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePurchaserName(p db_repo.Predicate, value string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchaser_name", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePurchaserNameIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchaser_name", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePurchaserNameNotIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchaser_name", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByPurchaserName(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "purchaser_name "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereFlowStatus(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "flow_status", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereFlowStatusIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "flow_status", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereFlowStatusNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "flow_status", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByFlowStatus(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "flow_status "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereCurFlowStatus(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "cur_flow_status", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereCurFlowStatusIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "cur_flow_status", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereCurFlowStatusNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "cur_flow_status", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByCurFlowStatus(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "cur_flow_status "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsArchive(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_archive", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsArchiveIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_archive", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsArchiveNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_archive", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByIsArchive(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "is_archive "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsRepeal(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_repeal", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsRepealIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_repeal", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsRepealNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_repeal", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByIsRepeal(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "is_repeal "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereNote(p db_repo.Predicate, value string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "note", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereNoteIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "note", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereNoteNotIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "note", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByNote(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "note "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereExaminePriceResult(p db_repo.Predicate, value string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "examine_price_result", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereExaminePriceResultIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "examine_price_result", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereExaminePriceResultNotIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "examine_price_result", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByExaminePriceResult(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "examine_price_result "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereExaminePriceKey(p db_repo.Predicate, value string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "examine_price_key", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereExaminePriceKeyIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "examine_price_key", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereExaminePriceKeyNotIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "examine_price_key", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByExaminePriceKey(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "examine_price_key "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereExaminePriceData(p db_repo.Predicate, value string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "examine_price_data", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereExaminePriceDataIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "examine_price_data", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereExaminePriceDataNotIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "examine_price_data", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByExaminePriceData(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "examine_price_data "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePushErp(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "push_erp", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePushErpIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "push_erp", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WherePushErpNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "push_erp", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByPushErp(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "push_erp "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsReal(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_real", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsRealIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_real", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsRealNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_real", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByIsReal(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "is_real "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSourceErpBillnumber(p db_repo.Predicate, value string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "source_erp_billnumber", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSourceErpBillnumberIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "source_erp_billnumber", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSourceErpBillnumberNotIn(value []string) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "source_erp_billnumber", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderBySourceErpBillnumber(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "source_erp_billnumber "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSourcePhsoid(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "source_phsoid", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSourcePhsoidIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "source_phsoid", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereSourcePhsoidNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "source_phsoid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderBySourcePhsoid(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "source_phsoid "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsSingle(p db_repo.Predicate, value int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_single", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsSingleIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_single", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereIsSingleNotIn(value []int32) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_single", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByIsSingle(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "is_single "+order)
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereDeliveryDate(p db_repo.Predicate, value time.Time) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "delivery_date", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereDeliveryDateIn(value []time.Time) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "delivery_date", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) WhereDeliveryDateNotIn(value []time.Time) *purchasehubSupplierOrderRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "delivery_date", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderRepoQueryBuilder) OrderByDeliveryDate(asc bool) *purchasehubSupplierOrderRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "delivery_date "+order)
	return qb
}
