///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package purchasehub_supplier_order_goods_index_repo

import (
	"fmt"
	"time"

	"go_service/repository/db_repo"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *PurchasehubSupplierOrderGoodsIndex {
	return new(PurchasehubSupplierOrderGoodsIndex)
}

func NewQueryBuilder() *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	return new(purchasehubSupplierOrderGoodsIndexRepoQueryBuilder)
}

func (t *PurchasehubSupplierOrderGoodsIndex) Create(db *gorm.DB) (id int32, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type purchasehubSupplierOrderGoodsIndexRepoQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&PurchasehubSupplierOrderGoodsIndex{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&PurchasehubSupplierOrderGoodsIndex{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&PurchasehubSupplierOrderGoodsIndex{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) First(db *gorm.DB) (*PurchasehubSupplierOrderGoodsIndex, error) {
	ret := &PurchasehubSupplierOrderGoodsIndex{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) QueryOne(db *gorm.DB) (*PurchasehubSupplierOrderGoodsIndex, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) QueryAll(db *gorm.DB) ([]*PurchasehubSupplierOrderGoodsIndex, error) {
	var ret []*PurchasehubSupplierOrderGoodsIndex
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) Limit(limit int) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) Offset(offset int) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) WhereId(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) WhereIdIn(value []int32) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) WhereIdNotIn(value []int32) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) OrderById(asc bool) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) WhereGoodsId(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_id", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) WhereGoodsIdIn(value []int32) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_id", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) WhereGoodsIdNotIn(value []int32) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) OrderByGoodsId(asc bool) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "goods_id "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) WherePhsoid(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsoid", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) WherePhsoidIn(value []int32) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsoid", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) WherePhsoidNotIn(value []int32) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsoid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) OrderByPhsoid(asc bool) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "phsoid "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) WhereUpdatedAt(p db_repo.Predicate, value time.Time) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) WhereUpdatedAtIn(value []time.Time) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) WhereUpdatedAtNotIn(value []time.Time) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) OrderByUpdatedAt(asc bool) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "updated_at "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) WhereCreatedAt(p db_repo.Predicate, value time.Time) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) WhereCreatedAtIn(value []time.Time) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) WhereCreatedAtNotIn(value []time.Time) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder) OrderByCreatedAt(asc bool) *purchasehubSupplierOrderGoodsIndexRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "created_at "+order)
	return qb
}
