///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package purchasehub_supplier_order_goods_sku_merge_repo

import (
	"fmt"
	"time"

	"go_service/repository/db_repo"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *PurchasehubSupplierOrderGoodsSkuMerge {
	return new(PurchasehubSupplierOrderGoodsSkuMerge)
}

func NewQueryBuilder() *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	return new(purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder)
}

func (t *PurchasehubSupplierOrderGoodsSkuMerge) Create(db *gorm.DB) (id int32, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&PurchasehubSupplierOrderGoodsSkuMerge{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&PurchasehubSupplierOrderGoodsSkuMerge{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&PurchasehubSupplierOrderGoodsSkuMerge{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) First(db *gorm.DB) (*PurchasehubSupplierOrderGoodsSkuMerge, error) {
	ret := &PurchasehubSupplierOrderGoodsSkuMerge{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) QueryOne(db *gorm.DB) (*PurchasehubSupplierOrderGoodsSkuMerge, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) QueryAll(db *gorm.DB) ([]*PurchasehubSupplierOrderGoodsSkuMerge, error) {
	var ret []*PurchasehubSupplierOrderGoodsSkuMerge
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) Limit(limit int) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) Offset(offset int) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) WhereId(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) WhereIdIn(value []int32) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) WhereIdNotIn(value []int32) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) OrderById(asc bool) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) WherePhsoid(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsoid", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) WherePhsoidIn(value []int32) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsoid", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) WherePhsoidNotIn(value []int32) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsoid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) OrderByPhsoid(asc bool) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "phsoid "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) WhereDetails(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "details", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) WhereDetailsIn(value []string) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "details", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) WhereDetailsNotIn(value []string) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "details", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) OrderByDetails(asc bool) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "details "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) WhereCreatedAt(p db_repo.Predicate, value time.Time) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) WhereCreatedAtIn(value []time.Time) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) WhereCreatedAtNotIn(value []time.Time) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) OrderByCreatedAt(asc bool) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "created_at "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) WhereUpdatedAt(p db_repo.Predicate, value time.Time) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) WhereUpdatedAtIn(value []time.Time) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) WhereUpdatedAtNotIn(value []time.Time) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder) OrderByUpdatedAt(asc bool) *purchasehubSupplierOrderGoodsSkuMergeRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "updated_at "+order)
	return qb
}
