///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package purchasehub_supplier_order_goods_sku_repo

import (
	"fmt"
	"time"

	"go_service/repository/db_repo"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *PurchasehubSupplierOrderGoodsSku {
	return new(PurchasehubSupplierOrderGoodsSku)
}

func NewQueryBuilder() *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	return new(purchasehubSupplierOrderGoodsSkuRepoQueryBuilder)
}

func (t *PurchasehubSupplierOrderGoodsSku) Create(db *gorm.DB) (id int32, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type purchasehubSupplierOrderGoodsSkuRepoQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&PurchasehubSupplierOrderGoodsSku{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&PurchasehubSupplierOrderGoodsSku{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&PurchasehubSupplierOrderGoodsSku{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) First(db *gorm.DB) (*PurchasehubSupplierOrderGoodsSku, error) {
	ret := &PurchasehubSupplierOrderGoodsSku{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) QueryOne(db *gorm.DB) (*PurchasehubSupplierOrderGoodsSku, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) QueryAll(db *gorm.DB) ([]*PurchasehubSupplierOrderGoodsSku, error) {
	var ret []*PurchasehubSupplierOrderGoodsSku
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) Limit(limit int) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) Offset(offset int) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereId(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereIdIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereIdNotIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderById(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePhsogid(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsogid", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePhsogidIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsogid", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePhsogidNotIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsogid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderByPhsogid(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "phsogid "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePhsoid(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsoid", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePhsoidIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsoid", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePhsoidNotIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phsoid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderByPhsoid(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "phsoid "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePhoid(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phoid", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePhoidIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phoid", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePhoidNotIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "phoid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderByPhoid(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "phoid "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereGoodsId(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_id", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereGoodsIdIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_id", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereGoodsIdNotIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderByGoodsId(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "goods_id "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereGoodsSn(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_sn", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereGoodsSnIn(value []string) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_sn", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereGoodsSnNotIn(value []string) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "goods_sn", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderByGoodsSn(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "goods_sn "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereSkuId(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sku_id", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereSkuIdIn(value []string) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sku_id", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereSkuIdNotIn(value []string) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sku_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderBySkuId(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "sku_id "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereSkuNumSn(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sku_num_sn", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereSkuNumSnIn(value []string) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sku_num_sn", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereSkuNumSnNotIn(value []string) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sku_num_sn", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderBySkuNumSn(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "sku_num_sn "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereUpdatedAt(p db_repo.Predicate, value time.Time) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereUpdatedAtIn(value []time.Time) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereUpdatedAtNotIn(value []time.Time) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "updated_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderByUpdatedAt(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "updated_at "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereCreatedAt(p db_repo.Predicate, value time.Time) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereCreatedAtIn(value []time.Time) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereCreatedAtNotIn(value []time.Time) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "created_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderByCreatedAt(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "created_at "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePrice(p db_repo.Predicate, value float64) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "price", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePriceIn(value []float64) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "price", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePriceNotIn(value []float64) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "price", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderByPrice(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "price "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereInPrice(p db_repo.Predicate, value float64) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "in_price", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereInPriceIn(value []float64) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "in_price", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereInPriceNotIn(value []float64) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "in_price", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderByInPrice(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "in_price "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePurchaseQuantity(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_quantity", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePurchaseQuantityIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_quantity", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePurchaseQuantityNotIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_quantity", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderByPurchaseQuantity(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "purchase_quantity "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePurchaseAmount(p db_repo.Predicate, value float64) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_amount", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePurchaseAmountIn(value []float64) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_amount", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePurchaseAmountNotIn(value []float64) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_amount", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderByPurchaseAmount(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "purchase_amount "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePurchaseOrderQuantity(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_quantity", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePurchaseOrderQuantityIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_quantity", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePurchaseOrderQuantityNotIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_quantity", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderByPurchaseOrderQuantity(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "purchase_order_quantity "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePurchaseOrderPrice(p db_repo.Predicate, value float64) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_price", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePurchaseOrderPriceIn(value []float64) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_price", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePurchaseOrderPriceNotIn(value []float64) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_price", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderByPurchaseOrderPrice(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "purchase_order_price "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePurchaseOrderAmount(p db_repo.Predicate, value float64) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_amount", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePurchaseOrderAmountIn(value []float64) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_amount", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WherePurchaseOrderAmountNotIn(value []float64) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "purchase_order_amount", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderByPurchaseOrderAmount(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "purchase_order_amount "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereDeliveryNum(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "delivery_num", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereDeliveryNumIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "delivery_num", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereDeliveryNumNotIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "delivery_num", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderByDeliveryNum(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "delivery_num "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereSuppSkuSn(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supp_sku_sn", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereSuppSkuSnIn(value []string) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supp_sku_sn", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereSuppSkuSnNotIn(value []string) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "supp_sku_sn", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderBySuppSkuSn(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "supp_sku_sn "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereStockNum(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "stock_num", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereStockNumIn(value []string) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "stock_num", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereStockNumNotIn(value []string) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "stock_num", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderByStockNum(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "stock_num "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereSizeEn(p db_repo.Predicate, value string) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "size_en", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereSizeEnIn(value []string) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "size_en", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereSizeEnNotIn(value []string) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "size_en", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderBySizeEn(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "size_en "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereStatus(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereStatusIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereStatusNotIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderByStatus(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "status "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereHangupQuantity(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "hangup_quantity", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereHangupQuantityIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "hangup_quantity", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereHangupQuantityNotIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "hangup_quantity", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderByHangupQuantity(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "hangup_quantity "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereIsHangup(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_hangup", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereIsHangupIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_hangup", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereIsHangupNotIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "is_hangup", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderByIsHangup(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "is_hangup "+order)
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereStockoutType(p db_repo.Predicate, value int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "stockout_type", p),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereStockoutTypeIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "stockout_type", "IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) WhereStockoutTypeNotIn(value []int32) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "stockout_type", "NOT IN"),
		value,
	})
	return qb
}

func (qb *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder) OrderByStockoutType(asc bool) *purchasehubSupplierOrderGoodsSkuRepoQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "stockout_type "+order)
	return qb
}
